services:
  - type: web
    runtime: node
    name: react-chat-backend
    env: node
    region: frankfurt
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 443
      - fromGroup: openai



  - type: web
    runtime: node
    name: react-chat-frontend
    region: frankfurt
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://my-app-backend.onrender.com
      - fromGroup: firebase
